#!/usr/bin/env python
"""Summarize per-node memory usage from a Nipype callback log."""

from __future__ import annotations

import csv
from argparse import ArgumentParser, RawTextHelpFormatter
from pathlib import Path

from xcp_d.utils.resource_monitor import summarize_callback_log


def get_parser():
    """Build parser object."""
    parser = ArgumentParser(description=__doc__, formatter_class=RawTextHelpFormatter)
    parser.add_argument(
        'callback_log',
        action='store',
        type=Path,
        help='Path to callback log generated by Nipype log_nodes_cb.',
    )
    parser.add_argument(
        '--output',
        action='store',
        type=Path,
        default=None,
        help='Optional TSV output path (default: <callback_log>_memory-summary.tsv).',
    )
    parser.add_argument(
        '--top',
        action='store',
        type=int,
        default=None,
        help='Only keep the top N nodes ranked by runtime-estimated memory delta.',
    )
    return parser


def main(args=None):
    """Run callback-log memory summarization."""
    opts = get_parser().parse_args(args)
    rows = summarize_callback_log(opts.callback_log)

    if opts.top is not None:
        rows = rows[: max(opts.top, 0)]

    if opts.output is None:
        output_path = opts.callback_log.with_name(f'{opts.callback_log.stem}_memory-summary.tsv')
    else:
        output_path = opts.output

    fieldnames = [
        'node_name',
        'estimated_memory_gb',
        'runtime_memory_gb',
        'delta_memory_gb',
        'runtime_vs_estimated_ratio',
        'n_samples',
    ]
    with output_path.open('w', newline='') as fobj:
        writer = csv.DictWriter(fobj, delimiter='\t', fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f'Wrote memory summary for {len(rows)} nodes to {output_path}')  # noqa: T201


if __name__ == '__main__':
    raise RuntimeError('this should be run as a command-line tool')
